apiVersion: v1
kind: Service
metadata:
  name: {{ project_name }}-api-service
  namespace: {{ project_name }}-project
spec:
  selector:
    app: {{ project_name }}-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: NodePort


---
apiVersion: v1
kind: Service
metadata:
  name: model-registry-service
  namespace: {{ project_name }}-project
spec:
  selector:
    app: model-registry
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort
