apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: registry-ingress
  namespace: default
spec:
  rules:
  - host: model-platform.com
    http:
      paths:
      - path: "/registry/"
        pathType: Prefix
        backend:
          service:
            name: nginx-reverse-proxy
            port:
              number: 80
      - path: "/deploy/"
        pathType: Prefix
        backend:
          service:
            name: nginx-reverse-proxy
            port:
              number: 80
      - path: "/pgsql/"
        pathType: Prefix
        backend:
          service:
            name: modelplatform-pgsql
            port:
              number: 5432
